source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'DGInfinity' do
pod 'AFNetworking', '~> 3.0'
pod 'YYWebImage'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'tingyunApp'
pod 'UMengAnalytics-NO-IDFA'
pod 'DZNEmptyDataSet'
pod 'AliyunOSSiOS'
pod 'Masonry'
end
